apiVersion: apps/v1
kind: Deployment
metadata:
  name: microservicio-java
spec:
  replicas: 2
  selector:
    matchLabels:
      app: microservicio-java
  template:
    metadata:
      labels:
        app: microservicio-java
    spec:
      containers:
      - name: microservicio-java
        image: jimenadev/microservicio-java:latest
        ports:
        - containerPort: 8080

---
apiVersion: v1
kind: Service
metadata:
  name: service-microservicio-java
spec:
  ports:
  - port: 8085
    targetPort: 8085
  selector:
    app: microservicio-java   
