name: CI
on:
  push:
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout (Clonacion de codigo)
        uses: actions/checkout@v4

      - name: Build (Setup Java JDK)
        uses: actions/setup-java@4
        with:
          java-version: '8'
          distribution: 'temurin'
      - name: Build (Compilacion)
        run: |
          mvn clean package
      
      - name: Unit Tests (Ejecucion Test Unitarios)
        run: |
            mvn package test