name: CI
on:
  push:
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout (Clonacion de codigo)
        uses: actions/checkout@v4

      - name: Build (Setup Java JDK)
        uses: actions/setup-java@master
        with:
          java-version: '8'
          distribution: 'temurin'

  coverage:
    needs: build
    runs-on: ubuntu-latest
        
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        
      - name: Set up JDK
        uses: actions/setup-java@master
        with:
          java-version: '8'
        
      - name: Generate coverage report
        run: mvn jacoco:prepare-agent jacoco:report
        
      - name: Verify coverage
        run: mvn jacoco:check