name: CI
on:
  push:
jobs:     
  deploy:
    runs-on: self-hosted
    steps:
        - name: Checkout (Clonación de código)
          uses: actions/checkout@v4
        - name: Despliegue
          run: |
             kubectl apply -f deploy.yaml
  test-performance:
    needs: deploy
    runs-on: self-hosted
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Ejecutar pruebas de rendimiento con k6
        run: k6 run --summary-export=./e2e/summary.json ./e2e/testk6-rendimiento.js
        env:
          K6_CLOUD_TOKEN: ${{ secrets.K6_TOKEN }}