name: CI
on:
  push:
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout (Clonacion de codigo)
        uses: actions/checkout@v4

      - name: Build (Setup Java JDK)
        uses: actions/setup-java@v2
        with:
          java-version: '8'
          distribution: 'temurin'
      - name: Build and test without coverage
        run: mvn clean verify -Djacoco.skip=true

  coverage:
    needs: build
    runs-on: ubuntu-latest
        
    steps:
      - name: Build and Test with JaCoCo
        run: |
          mvn clean verify
          mvn jacoco:prepare-agent
          mvn jacoco:report

      - name: Upload JaCoCo report
        uses: actions/upload-artifact@v2
        with:
           name: jacoco-report
           path: target/site/jacoco/