name: CI
on:
  push:
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout (Clonación de código)
        uses: actions/checkout@v4
      - name: Build (Setup Java JDK)
        uses: actions/setup-java@v4
        with:
          java-version: '8'
          distribution: 'temurin'
      - name: Build (Compilación)
        run: |
          mvn package       
  deploy:
    needs: build
    runs-on: self-hosted
    steps:
        - name: Checkout (Clonación de código)
          uses: actions/checkout@v4
        - name: Despliegue
          run: |
             kubectl apply -f deploy.yaml
  test-performance:
    needs: deploy
    runs-on: self-hosted
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Ejecutar pruebas de rendimiento con k6
        run: k6 run --summary-export=./e2e/summary.json ./e2e/testk6-rendimiento.js
        env:
          K6_CLOUD_TOKEN: ${{ secrets.K6_TOKEN }}
      - name:  Upload report to k6 cloud
        uses: actions/upload-artifact@v3
        with:
          name: k6-report
          path: ./e2e/summary.json 
        env:
          K6_CLOUD_TOKEN: ${{ secrets.K6_TOKEN }}